package APIServer;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.UUID;

import org.restlet.Request;
import org.restlet.data.Form;
import org.restlet.data.MediaType;
import org.restlet.representation.FileRepresentation;
import org.restlet.resource.Get;
import org.restlet.resource.ServerResource;

/**
 * Return wave files generated by calling festival in Terminal.
 * We put all the wave files into folder GeneratedWave
 * the file will be deleted after having been sent to the client
 */

public class SayEmotional extends ServerResource{
	String txt = "";
	String errorWave = Main.errorWave;
	String noAuthorityWave = Main.noAuthorityWave;
	String wavePath = Main.wavePath;
	String festivalHome = Main.festivalHome;
	String voice = Main.defaultVoice;
	String emotion = Main.defaultEmotion;
	String level = Main.defaultLevel;
	String token = "";
	
	@Get
    public FileRepresentation getResource() {
		FileRepresentation result = new FileRepresentation(errorWave,MediaType.AUDIO_WAV);
		Request request = getRequest();
		Form form = request.getResourceRef().getQueryAsForm();
		if(form.getValues("txt") != null && form.getValues("txt") != "")
		{
			txt = form.getValues("txt");
		}
		else
		{
			System.out.println("query string txt is null");
		}		
		if(form.getValues("voice") != null && form.getValues("voice") != "")
		{
			voice = form.getValues("voice");
		}
		if(form.getValues("emotion") != null && form.getValues("emotion") != "")
		{
			emotion = form.getValues("emotion");
		}
		if(form.getValues("level") != null && form.getValues("level") != "")
		{
			level = form.getValues("level");
		}
		if(form.getValues("token") != null && form.getValues("token") != "")
		{
			token = form.getValues("token");
			if (token.equals(Main.token))
			{		
				result = process(txt);		
			}
			else
			{
				result = new FileRepresentation(noAuthorityWave,MediaType.AUDIO_WAV);
			}	
		}
		else
		{
			System.out.println("query string token is null");
			result = new FileRepresentation(noAuthorityWave,MediaType.AUDIO_WAV);
		}		
		return result; 
    }

	private FileRepresentation process(String txt){		
		FileRepresentation result = new FileRepresentation(errorWave,MediaType.AUDIO_WAV);
		String waveFilePath = "";
		waveFilePath = wavePath + GenerateUid() + ".wav";
		String scriptFile = generateScriptFile(txt);		
		String[] Command = {"/bin/sh", "-c", "cd " + festivalHome +"; ./" + "festival " + "--batch " + scriptFile};

		if(excuteCommand(Command))
		{
			result = new FileRepresentation(waveFilePath,MediaType.AUDIO_WAV);		
		}
		else
		{
			System.out.println("Generate wav file error");	
		}
		return result;
	}	
		
	private String GenerateUid()
	{
		return UUID.randomUUID().toString();
	}
	
	private String generateScriptFile(String txt)
	{
		String fileName = "";
		String uniqueID = GenerateUid();
		fileName = wavePath + uniqueID + "_script";
		try {
			File scriptFile = new File(fileName);
			FileWriter fw;

			fw = new FileWriter(scriptFile.getAbsoluteFile());
			String changeVoice = "(" + voice + ")";
			String sayEmotional = "(utt.save.wave (SayEmotional '" + emotion + " \"" + txt + "\" " + level +") " + "\"" + fileName + "\")";
			String quit = "(quit)";
			BufferedWriter bw = new BufferedWriter(fw);
			bw.write(changeVoice);
			bw.write(System.getProperty("line.separator"));
			bw.write(sayEmotional);
			bw.write(System.getProperty("line.separator"));
			bw.write(quit);
			bw.close();
			
			if (!scriptFile.exists()){
				System.out.println("Generate txt file error");	
			}
				
		} catch (IOException e) {
			e.printStackTrace();
		}  catch (SecurityException e) {
			   e.printStackTrace();
			  }

		return fileName;
	}
	
	
	private boolean excuteCommand(String[] command) 
	{
		boolean result = false;
		Process p;
		try {
			p = Runtime.getRuntime().exec(command);
			p.waitFor();
			result = true;
		} catch (Exception e) {
			e.printStackTrace();
		}		
		return result;
	}
	
}
